name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push To Registry
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.6.0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.bramhampton.ml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: docker.bramhampton.ml/discord-openai:latest
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://portainer.bramhampton.ml/api/webhooks/40e2541e-bc5b-4cea-a741-bc5262011d30'
        method: 'POST'
