name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push To Registry
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64,linux/amd64
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        registry: docker.bramhampton.ml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: docker.bramhampton.ml/bram/discord-openai:latest