name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push To Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.6.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.bramhampton.ml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm32v7
        push: true
        tags: docker.bramhampton.ml/discord-openai:latest
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://portainer.bramhampton.ml/api/webhooks/4f3ca2a9-9c92-4459-914f-34a399980a32'
        method: 'POST'
