name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push To Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.6.0
    - name: Build image
      id: build
      uses: redhat-actions/buildah-build@v2.11
      with:
        containerfiles: Dockerfile
        image: bram/discord-openai
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: bram/discord-openai
        registry: docker.bramhampton.ml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
