name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push To Registry
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.6.0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.bramhampton.ml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm32v7
        push: true
        tags: docker.bramhampton.ml/discord-openai:latest
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://portainer.bramhampton.ml/api/webhooks/21da7f14-88d0-42f0-aaba-0e744061c6f9'
        method: 'POST'
